# Generated by Django 5.2.17 on 2026-09-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=15)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('exit_price_2', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=5)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('feeling', models.CharField(blank=True, choices=[('VERY_BULLISH', 'Très haussier'), ('BULLISH', 'Haussier'), ('NEUTRAL', 'Neutre'), ('BEARISH', 'Baissier'), ('VERY_BEARISH', 'Très baissier')], max_length=20)),
                ('why', models.TextField(blank=True, help_text='Raison de la prise de position')),
            ],
            options={
                'verbose_name': 'Futures Trading',
                'verbose_name_plural': 'Futures Tradings',
                'db_table': 'core_futures_trading',
            },
        ),
        migrations.CreateModel(
            name='SpotTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=15)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('exit_price_2', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.CharField(choices=[('BINANCE', 'Binance'), ('KRAKEN', 'Kraken'), ('COINBASE', 'Coinbase'), ('OTHER', 'Autre')], default='BINANCE', max_length=20)),
            ],
            options={
                'verbose_name': 'Spot Trading',
                'verbose_name_plural': 'Spot Tradings',
                'db_table': 'core_spot_trading',
            },
        ),
    ]
