# Generated by Django 5.2.17 on 2026-09-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=15)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('exit_price_2', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Simple Investment',
                'verbose_name_plural': 'Simple Investments',
                'db_table': 'core_simple_investment',
            },
        ),
    ]
