# Generated by Django 5.2.17 on 2026-09-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_simpleinvestment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleinvestment',
            name='entry_price',
        ),
        migrations.RemoveField(
            model_name='simpleinvestment',
            name='exit_price',
        ),
        migrations.RemoveField(
            model_name='simpleinvestment',
            name='exit_price_2',
        ),
        migrations.AddField(
            model_name='simpleinvestment',
            name='action',
            field=models.CharField(choices=[('ACHAT', 'Achat'), ('VENTE', 'Vente')], default='ACHAT', max_length=5),
        ),
        migrations.AddField(
            model_name='simpleinvestment',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
