# Generated by Django 5.2.17 on 2026-09-06 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_simpleinvestment_entry_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleinvestment',
            name='external_ref',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='simpleinvestment',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
