# Generated by Django 5.2.17 on 2026-09-07 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_simpleinvestment_external_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestrading',
            name='strategy',
            field=models.CharField(blank=True, help_text='Nom de la stratégie utilisée (ex: IRC 4h, VP 15min)', max_length=50),
        ),
        migrations.AlterField(
            model_name='futurestrading',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spottrading',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
