# Generated by Django 5.2.17 on 2026-09-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_futurestrading_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestrading',
            name='trade_mode',
            field=models.CharField(choices=[('PAPER', 'Paper'), ('LIVE', 'Live')], default='PAPER', help_text='Position réelle (Live) ou fictive (Paper)', max_length=5),
        ),
    ]
