# Generated by Django 5.2.17 on 2026-09-09

from django.db import migrations, models


def mark_existing_spot_trades_live(apps, schema_editor):
    """Preserve manually recorded historical spot trades as real trades."""
    SpotTrading = apps.get_model('core', 'SpotTrading')
    SpotTrading.objects.update(trade_mode='LIVE')


def mark_existing_spot_trades_paper(apps, schema_editor):
    """Restore the pre-feature default when rolling this migration back."""
    SpotTrading = apps.get_model('core', 'SpotTrading')
    SpotTrading.objects.update(trade_mode='PAPER')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_futurestrading_trade_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestrading',
            name='external_ref',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='futurestrading',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='futurestrading',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='spottrading',
            name='external_ref',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='spottrading',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='spottrading',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='spottrading',
            name='trade_mode',
            field=models.CharField(
                choices=[('PAPER', 'Paper'), ('LIVE', 'Live')],
                default='PAPER',
                help_text='Position réelle (Live) ou fictive (Paper)',
                max_length=5,
            ),
        ),
        migrations.RunPython(mark_existing_spot_trades_live, mark_existing_spot_trades_paper),
    ]