# Generated by Django 5.2.17 on 2026-09-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_futurestrading_external_ref_futurestrading_stop_loss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('KRAKEN', 'Kraken'), ('BINANCE', 'Binance'), ('BITGET', 'Bitget'), ('COINMARKETCAP', 'CoinMarketCap'), ('OTHER', 'Autre')], max_length=20)),
                ('label', models.CharField(blank=True, help_text="Nom libre pour distinguer plusieurs clés d'une même plateforme", max_length=50)),
                ('api_key', models.TextField(help_text='Chiffré en BDD')),
                ('api_secret', models.TextField(blank=True, help_text='Chiffré en BDD')),
                ('passphrase', models.TextField(blank=True, help_text='Chiffré en BDD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clé API',
                'verbose_name_plural': 'Clés API',
                'db_table': 'core_api_credential',
                'ordering': ['platform', 'label'],
            },
        ),
    ]
