# Generated by Django 5.2.17 on 2026-09-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_kraken_credential_from_env'),
    ]

    operations = [
        migrations.CreateModel(
            name='KrakenNonceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_kraken_nonce_counter',
            },
        ),
        migrations.AddField(
            model_name='futurestrading',
            name='is_closing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spottrading',
            name='is_closing',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='KrakenOrderAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_order_id', models.CharField(max_length=32, unique=True)),
                ('kraken_userref', models.BigIntegerField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('OPEN', 'Ouverture'), ('CLOSE', 'Clôture')], max_length=5)),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=4)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', "En attente d'envoi"), ('SUBMITTED', 'Soumis à Kraken'), ('CONFIRMED', 'Confirmé (position à jour)'), ('FAILED', 'Échec avant confirmation Kraken'), ('RECONCILE_REQUIRED', 'Réconciliation manuelle requise')], default='PENDING', max_length=20)),
                ('external_ref', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spot_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kraken_attempts', to='core.spottrading')),
            ],
            options={
                'verbose_name': 'Tentative ordre Kraken',
                'verbose_name_plural': 'Tentatives ordres Kraken',
                'db_table': 'core_kraken_order_attempt',
                'ordering': ['-created_at'],
            },
        ),
    ]
