# Generated by Django 5.2.17 on 2026-09-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_krakennoncecounter_futurestrading_is_closing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatcherHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_watcher_heartbeat',
            },
        ),
    ]
