# Generated by Django 5.2.17 on 2026-09-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_require_user_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestrading',
            name='timeframe',
            field=models.CharField(blank=True, help_text='Time frame utilisé (ex: 15min, 1h, 4h, 1D)', max_length=20),
        ),
        migrations.AddField(
            model_name='spottrading',
            name='timeframe',
            field=models.CharField(blank=True, help_text='Time frame utilisé (ex: 15min, 1h, 4h, 1D)', max_length=20),
        ),
    ]
