# Generated by Django 5.2.17 on 2026-09-22 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredentialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('READ', 'Lecture (déchiffrement)'), ('DELETE', 'Suppression')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.apicredential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_credential_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'accès clé API",
                'verbose_name_plural': "Journal d'accès clés API",
                'db_table': 'core_api_credential_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
