# Generated by Django 5.2.17 on 2026-09-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_apicredentialauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='tracked_assets',
            field=models.JSONField(blank=True, default=list, help_text='Liste des symboles (ex: BTC, ETH) utilisés pour filtrer les news Vigil sur la page Trading.'),
        ),
    ]
